services:
  - type: web
    name: telegram-dice-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
      - key: FLASK_ENV
        value: production
